### ISSUE TITLE
I met compiling error while compiling:  no known conversion from ‘cv::DenseOpticalFlow*’ to ‘int’

### ISSUE THREAD

**Issue by lixiangpengcs** [gulvarol/flow_toolbox#1]
I use opencv version is 2.4.13.6 and I don't know why I met this problem. what version opencv do you use while compiling.
/usr/local/include/opencv2/core/operations.hpp:2647:31: note:   no known conversion from ‘cv::DenseOpticalFlow*’ to ‘int’

**Comment by gulvarol** [comment]
I used OpenCV 3, sorry for the lack of documentation. For OpenCV 2.4, you can have a look at this example: https://github.com/opencv/opencv/blob/2.4/samples/gpu/optical_flow.cpp
